apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homarr-ingressroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`homarr.local`)
      kind: Rule
      services:
        - name: homarr-service
          port: 80
