apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homarr-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: homarr.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homarr-service
            port:
              number: 80
  - host: mealie.local.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
        service:
          name: mealie-service
          port:
          number: 80
