apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multi-service-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
        - path: /homarr
          pathType: Prefix
          backend:
            service:
              name: homarr-service
              port:
                number: 80
        - path: /mealie
          pathType: Prefix
          backend:
            service:
              name: mealie-service
              port:
                number: 80
