apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multi-service-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: homarr.local
      http:
        paths:
          - path: /homarr
            pathType: Prefix
            backend:
              service:
                name: homarr-service
                port:
                  number: 80
    - host: mealie.local.com
      http:
        paths:
          - path: /mealie
            pathType: Prefix
            backend:
              service:
                name: mealie-service
                port:
                  number: 80
